sudo: required

services:
  - docker

before_install:
  - docker build -t frontend_test -f Dockerfile.dev .

script:
  - docker run -e CI=true frontend_test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend-react"
  env: "FrontendReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-609596248833"
  bucket_path: "frontend-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
